name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  UI-Tests:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [21, 17]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Print Working Directory and Home Folder
        run: |
            echo "Working Directory: $(pwd)"
            echo "Home Directory: $HOME"
  
      - name: Clean up previous test output
        run: |
          rm -rf Test-Output/Reports/*
          rm -rf Test-Output/Logs/*
          rm -rf Test-Output/ScreenShots/Failed/*
          find Test-Output/UpdateChecker/ -type f ! -name 'checker.json' -delete

      - name: Run Tests
        run: mvn clean test -Dtest="loginTests,AlertsTests,HorizontalSliderTests,DropDownTests,DragDropTests,HoverPageTests,DynamicLoadingPageTests" -Dsurefire.parallel=classes -DthreadCount=7 -DdataProviderThreadCount=7

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: ./Test-Output/Reports/
          retention-days: 30

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: Test-Logs
          path: ./Test-Output/Logs/
          retention-days: 30

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Failed-Screenshots
          path: ./Test-Output/ScreenShots/Failed/
          retention-days: 30

      - name: Upload Update Checker
        uses: actions/upload-artifact@v4
        with:
          name: Update-Checker
          path: ./Test-Output/UpdateChecker/
          retention-days: 30